### ISSUE TITLE
chore: Update Thema/Components version static strings in automated PRs

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#859] opened 2020-11-25 16:37 UTC
Currently when a dependency [update PR is made by Renovate](https://github.com/stencila/hub/pull/857), the static strings for Thema/Components versions [need to be manually updated](https://github.com/stencila/hub/pull/857/commits/7d988a0d622496065e3b1acbb9f4a32fa3678c9e) by running `npm run install` or `npm run build:py` inside the `manager` directory.
To avoid forgetting to perform this step, and streamline the dependency update process, we should run the command and commit the updated files as part of the automated CI process.

**Comment by nokome** [comment] 2020-12-20 23:29
Not quite what was proposed in this issue but has the same outcome and consistent with our approach to committing other generated files: 2b5e00ffd238c791c88c4d098026f762110593ee. An example of result: 4f1e4816ced20c6d9b44343dabf328479bed8cef

Closing but feel free to re-open, if you really want it to happen on PR branches, not just on releases

**Closed by nokome** 2020-12-20 23:29 UTC
Labels: good first issue

**Comment by nokome** [comment] 2021-02-03 02:47
Just confirming to myself that this is still working as intended, example commit with updates to these files on CI: 86c0bca9fa2d92f9d994294fae702d2f636600b1
