### ISSUE TITLE
Hub fails to convert JATS XML due to missing --from flag

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#663] opened 2020-08-28 00:42 UTC
Attempting to import and convert an eLife article to RMD fails due on the Hub.
The issue seems to be an incorrect detection of the source `mimetype`, as I'm able to reproduce the issue directly with a local copy of Encoda. The generated file only contains `!null` as its contents.
Adding a `--from jats` flag to the convert command successfully converts the file.

**To reproduce:**

- Create a project on the Hub
- Add an eLife article as source (https://elifesciences.org/articles/43154)
- Pull sources
- Convert the `xml` file to `rmd`
- Download converted file to see it only contains `!null`

**Comment by nokome** [comment] 2020-08-28 02:18
Thanks for this Alex. Some diagnosis....

1. The mimetype of the JATS file is correctly set (by the worker's `pull_elife` function):

![image](https://user-images.githubusercontent.com/1152336/91513467-82caf180-e938-11ea-962b-692b60ddb4ba.png)

2. The mimetype is not sent as a parameter of the `convert` job:

![image](https://user-images.githubusercontent.com/1152336/91513632-e81ee280-e938-11ea-87d8-873ef2431465.png)

The offending method is:

https://github.com/stencila/hub/blob/0cb9697c7f65236db2a8e10d4d126a05a50194c5/manager/projects/models/files.py#L521-L536

**Comment by nokome** [comment] 2020-08-28 02:36
Unfortunately Encoda no longer accepts a mimetype in the `--from` option. I'm pretty sure it used to / was intended to. Sor a change will be required there also (to avoid duplication of mimetype to codec mappings in the Hub _and_ in Encoda)

```sh
> encoda convert article.xml --from application/jats+xml temp.rmd
⚠ WARN  encoda:xml Unable to decode XML document
> encoda convert article.xml --from jats temp.rmd # OK
```

**Comment by nokome** [comment] 2020-08-28 08:21
Reopening as not completely fixed yet

**Comment by nokome** [comment] 2020-09-07 05:00
Confirming that this is now fixed.

**Closed by nokome** 2020-09-07 05:00 UTC
Labels: released
