### ISSUE TITLE
Add django-oauth-toolkit

### ISSUE THREAD

**Issue by nokome** [stencila/hub#10] opened 2015-12-20 01:56 UTC
Needed to allow access from other sites e.g PubSweet. See .https://github.com/stencila/stencila/issues/86 

See https://django-oauth-toolkit.readthedocs.org/en/latest/

**Comment by apawlik** [comment] 2018-08-16 05:51
This will currently be a part of continuous integration for reproducible publishing - also since the code has been refactored. Closing for now.

**Closed by apawlik** 2018-08-16 05:51 UTC
