### ISSUE TITLE
Download snapshot returns 500 Internal Server Error

### ISSUE THREAD

**Issue by FAtherden-eLife** [stencila/hub#895] opened 2020-12-08 09:23 UTC
Download snapshot:
<img width="1196" alt="Screenshot 2020-12-08 at 09 19 09" src="https://user-images.githubusercontent.com/43879983/101464471-98d44f00-3936-11eb-83ff-07041f597efc.png">

currently returns a 500 Internal Server Error:
<img width="428" alt="Screenshot 2020-12-08 at 09 23 39" src="https://user-images.githubusercontent.com/43879983/101464835-18621e00-3937-11eb-9916-67e11f8dd518.png">

Examples:
https://hub.stenci.la/api/projects/518/snapshots/15/archive
https://hub.stenci.la/api/projects/583/snapshots/13/archive
https://hub.stenci.la/api/projects/588/snapshots/26/archive
https://hub.stenci.la/api/projects/1316/snapshots/14/archive

**Comment by nokome** [comment] 2020-12-09 01:24
Thanks for reporting this @FAtherden-eLife

- This bug has been fixed in https://github.com/stencila/hub/commit/118d1c009dbb0bd951e3a37e85bcf42ec3456268, and deployed in v4.24.3

- It was caused by the internal location `@account-content` not being in the appropriate Nginx `server` block

- The error first appeared in Nginx logs at 2020/12/07 00:49:04 UTC `[error] 7#7: *1754 could not find named location "@account-content" while reading response header from upstream...` just after the deployment of v4.24.0

- The `@account-content` location had been in the wrong server block for some time but it seems that location had not actually been used until this commit 90cf983e6e0eff387eba634ee06f4c80fa0ede9d

- We were not alerted of this error until this issue was raised. There was already a mechanism in place to report Nginx 502 and 504 errors to Sentry. This has now been expanded to include all 500 errors.

**Comment by nokome** [comment] 2020-12-09 01:33
I have also created a related issue here: https://github.com/stencila/hub/issues/898

**Comment by nokome** [comment] 2020-12-09 08:41
Unfortunately there seems to be some sort of regression here such that now the archives are being served but not images. Will re-add the original (now duplicate) `@account-content` location as an attempt at a quick fix.

**Comment by nokome** [comment] 2020-12-09 08:52
Hot fix to router worked but will hold of pushing the fix to `master` until tomorrow morning following more testing.

**Closed by nokome** 2020-12-09 08:52 UTC
